language: java
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2
  
stages:
  - Linting
  - Tests
  - Release

jobs:
  include:
    - stage: Linting
      script: mvn validate
    - stage: Tests
      script: echo tests
    - stage: Release 
      if: tag IS present
      script: echo release
      

