language: java
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2
  
jobs:
  include:
    - script: echo tests
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true
